import { generateId, updateDerivedState } from './state.js';
import { saveCampaign, notify } from './firebase-manager.js';

/**
 * NPC Generator Adapter (Web App Pure)
 * Provides a UI and logic to generate NPCs and add them directly to the Codex.
 */

export const openNpcGeneratorUI = () => {
    const container = document.getElementById('global-popup-container');
    if (!container) return;

    // A simple, pure web-app form for NPC generation
    container.innerHTML = `
        <div class="fixed inset-0 bg-stone-900 bg-opacity-80 flex items-center justify-center p-4 z-[18000] backdrop-blur-sm animate-in">
            <div class="bg-[#f4ebd8] p-6 rounded-sm border-2 border-stone-700 shadow-2xl max-w-sm w-full">
                <h3 class="text-lg font-serif font-bold text-stone-900 mb-4 border-b border-[#d4c5a9] pb-2">Generate New NPC</h3>
                <div class="space-y-4 mb-6">
                    <div>
                        <label class="text-xs font-bold text-stone-600 uppercase tracking-widest block mb-1">Full Name</label>
                        <input type="text" id="npc-gen-name" class="w-full p-2 border border-[#d4c5a9] rounded-sm text-sm" placeholder="e.g. Eldrin the Wise">
                    </div>
                    <div>
                        <label class="text-xs font-bold text-stone-600 uppercase tracking-widest block mb-1">Race</label>
                        <input type="text" id="npc-gen-race" class="w-full p-2 border border-[#d4c5a9] rounded-sm text-sm" placeholder="e.g. Wood Elf">
                    </div>
                </div>
                <div class="flex justify-end gap-2">
                    <button onclick="document.getElementById('global-popup-container').innerHTML = '';" class="px-4 py-2 text-stone-600 font-bold uppercase tracking-wider text-[10px]">Cancel</button>
                    <button onclick="window.appActions.addNpcToCodex()" class="px-4 py-2 bg-stone-900 text-amber-50 font-bold uppercase tracking-wider text-[10px] rounded-sm hover:bg-stone-800 shadow-md">Add to Codex</button>
                </div>
            </div>
        </div>
    `;
};

export const addNpcToCodex = async () => {
    const name = document.getElementById('npc-gen-name')?.value.trim();
    const race = document.getElementById('npc-gen-race')?.value.trim();

    if (!name) {
        notify("NPC must have a name.", "error");
        return;
    }

    updateDerivedState();
    const camp = window.appData.activeCampaign;
    if (!camp) return;

    const newEntry = {
        id: generateId(),
        name: name,
        type: 'NPC',
        tags: ['Generated', race].filter(Boolean),
        desc: "An NPC generated by the archives.",
        authorId: window.appData.currentUserUid,
        visibility: { mode: 'public' },
        race: race || ''
    };

    // Append to Codex
    camp.codex = [...(camp.codex || []), newEntry];
    
    // Save to Firestore
    await saveCampaign(camp);
    
    document.getElementById('global-popup-container').innerHTML = '';
    notify(`${name} successfully added to the Codex.`, "success");
    
    if (window.appActions.reRender) window.appActions.reRender();
};

if (typeof window !== 'undefined') {
    window.appActions = window.appActions || {};
    window.appActions.openNpcGeneratorUI = openNpcGeneratorUI;
    window.appActions.addNpcToCodex = addNpcToCodex;
}
